<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Clipora.Core\Clipora.Core.csproj" />
    <ProjectReference Include="..\..\src\Clipora.FFmpeg\Clipora.FFmpeg.csproj" />
    <ProjectReference Include="..\Clipora.FFmpeg.TestHost\Clipora.FFmpeg.TestHost.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <Target Name="CopyRunnerTestHost" AfterTargets="Build">
    <ItemGroup>
      <RunnerTestHostFiles Include="..\Clipora.FFmpeg.TestHost\bin\$(Configuration)\net10.0\Clipora.FFmpeg.TestHost.*" />
    </ItemGroup>
    <Copy SourceFiles="@(RunnerTestHostFiles)" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" />
  </Target>

</Project>
